test_dir = fileparts (mfilename ("fullpath"));
repo_root = fileparts (test_dir);

addpath (fullfile (repo_root, "inst"));
addpath (fullfile (repo_root, "src"));
addpath (test_dir);

assert (test (fullfile (test_dir, "build_probe.tst"), "quiet", stdout));
fprintf ("PASS: M01 build probe tests\n");
assert (test (fullfile (test_dir, "native_value.tst"), "quiet", stdout));
fprintf ("PASS: M02 native-value tests\n");
assert (test (fullfile (test_dir, "constructor.tst"), "quiet", stdout));
fprintf ("PASS: M03 public scalar constructor tests\n");
assert (test (fullfile (test_dir, "precision.tst"), "quiet", stdout));
fprintf ("PASS: M04 public precision tests\n");
assert (test (fullfile (test_dir, "conversion.tst"), "quiet", stdout));
fprintf ("PASS: M05 scalar conversion and display tests\n");
assert (test (fullfile (test_dir, "arithmetic.tst"), "quiet", stdout));
fprintf ("PASS: M06 scalar arithmetic tests\n");
assert (test (fullfile (test_dir, "matrix_storage.tst"), "quiet", stdout));
fprintf ("PASS: M07 native dense matrix storage tests\n");
assert (test (fullfile (test_dir, "gemm.tst"), "quiet", stdout));
fprintf ("PASS: M08 native MPFR Rgemm matrix multiplication tests\n");
assert (test (fullfile (test_dir, "gesv.tst"), "quiet", stdout));
fprintf ("PASS: M09 native MPFR Rgesv linear solve tests\n");
assert (test (fullfile (test_dir, "rgels.tst"), "quiet", stdout));
fprintf ("PASS: M15 native MPFR Rgels rectangular solve tests\n");
assert (test (fullfile (test_dir, "rank.tst"), "quiet", stdout));
fprintf ("PASS: M16 native rank-revealing rectangular solve tests\n");
assert (test (fullfile (test_dir, "chol.tst"), "quiet", stdout));
fprintf ("PASS: M17 native MPFR Rpotrf Cholesky tests\n");
assert (test (fullfile (test_dir, "qr.tst"), "quiet", stdout));
fprintf ("PASS: M18 native MPFR Rgeqrf/Rorgqr QR tests\n");
assert (test (fullfile (test_dir, "pivoted_qr.tst"), "quiet", stdout));
fprintf ("PASS: M19 native MPFR Rgeqp3/Rorgqr pivoted QR tests\n");
assert (test (fullfile (test_dir, "lu.tst"), "quiet", stdout));
fprintf ("PASS: M21 native MPFR Rgetrf LU tests\n");
assert (test (fullfile (test_dir, "matrix_inspection.tst"), "quiet", stdout));
fprintf ("PASS: M10 dense matrix inspection tests\n");
assert (test (fullfile (test_dir, "elementwise.tst"), "quiet", stdout));
fprintf ("PASS: M11 dense element-wise arithmetic tests\n");
assert (test (fullfile (test_dir, "structure.tst"), "quiet", stdout));
fprintf ("PASS: M12 dense transpose and reshape tests\n");
assert (test (fullfile (test_dir, "concat.tst"), "quiet", stdout));
fprintf ("PASS: M13 dense concatenation tests\n");
assert (test (fullfile (test_dir, "assignment.tst"), "quiet", stdout));
fprintf ("PASS: M14 dense indexed assignment tests\n");
assert (test (fullfile (test_dir, "release_closure.tst"), "quiet", stdout));
fprintf ("PASS: M22 real API and release closure tests\n");
assert (test (fullfile (test_dir, "complex_scalar.tst"), "quiet", stdout));
fprintf ("PASS: C01 complex scalar construction and conversion tests\n");
assert (test (fullfile (test_dir, "complex_matrix.tst"), "quiet", stdout));
fprintf ("PASS: C02 complex dense matrix tests\n");
assert (test (fullfile (test_dir, "complex_structural.tst"), "quiet", stdout));
fprintf ("PASS: C03 complex structural tests\n");
assert (test (fullfile (test_dir, "complex_elementwise.tst"), "quiet", stdout));
fprintf ("PASS: C04 complex element-wise tests\n");
assert (test (fullfile (test_dir, "complex_gemm.tst"), "quiet", stdout));
fprintf ("PASS: C05 complex Cgemm tests\n");
assert (test (fullfile (test_dir, "complex_gesv.tst"), "quiet", stdout));
fprintf ("PASS: C06 complex Cgesv tests\n");
assert (test (fullfile (test_dir, "complex_rank.tst"), "quiet", stdout));
fprintf ("PASS: C07 complex rank-revealing tests\n");
assert (test (fullfile (test_dir, "complex_cholesky.tst"), "quiet", stdout));
fprintf ("PASS: C08 complex Cholesky tests\n");
assert (test (fullfile (test_dir, "complex_qr.tst"), "quiet", stdout));
fprintf ("PASS: C09 complex QR tests\n");
assert (test (fullfile (test_dir, "complex_pivoted_qr.tst"), "quiet", stdout));
fprintf ("PASS: C10 complex pivoted QR tests\n");
assert (test (fullfile (test_dir, "complex_mixed_closure.tst"), "quiet", stdout));
fprintf ("PASS: C11 mixed real/complex closure tests\n");
assert (test (fullfile (test_dir, "complex_lu.tst"), "quiet", stdout));
fprintf ("PASS: C11L complex Cgetrf LU tests\n");
assert (test (fullfile (test_dir, "complex_release_firewall.tst"), "quiet", stdout));
fprintf ("PASS: C12 complex compatibility firewall tests\n");
assert (test (fullfile (test_dir, "norm.tst"), "quiet", stdout));
fprintf ("PASS: N00 norm tests\n");
assert (test (fullfile (test_dir, "det_inv.tst"), "quiet", stdout));
fprintf ("PASS: N01 determinant and inverse tests\n");
assert (test (fullfile (test_dir, "svd.tst"), "quiet", stdout));
fprintf ("PASS: N02 SVD tests\n");
run (fullfile (test_dir, "test_svd_tiers.m"));
run (fullfile (test_dir, "test_svd_verification.m"));
assert (test (fullfile (test_dir, "rank_condition.tst"), "quiet", stdout));
fprintf ("PASS: N03 rank and condition tests\n");
assert (test (fullfile (test_dir, "eig_structured.tst"), "quiet", stdout));
fprintf ("PASS: N04 structured symmetric/Hermitian eig tests\n");
assert (test (fullfile (test_dir, "eig_general.tst"), "quiet", stdout));
fprintf ("PASS: N05 general eig and Grcar tests\n");
assert (test (fullfile (test_dir, "eig_generalized.tst"), "quiet", stdout));
fprintf ("PASS: N06 generalized eig and QZ/Cholesky tests\n");
run (fullfile (test_dir, "test_nonsymmetric_eig_suite.m"));
fprintf ("PASS: NEIG difficult nonsymmetric eigensystem suite\n");
assert (test (fullfile (test_dir, "t00_schur_qz.tst"), "quiet", stdout));
fprintf ("PASS: T00 Hessenberg, balance, Schur, and QZ tests\n");
assert (test (fullfile (test_dir, "t01_dense_utilities.tst"), "quiet", stdout));
fprintf ("PASS: T01 pinv, null, orth, rref, and kron tests\n");
assert (test (fullfile (test_dir, "t02_matrix_functions.tst"), "quiet", stdout));
fprintf ("PASS: T02 expm, logm, and sqrtm tests\n");
assert (test (fullfile (test_dir, "t03_polynomial_core.tst"), "quiet", stdout));
fprintf ("PASS: T03 polynomial core tests\n");
assert (test (fullfile (test_dir, "t04_exact_sets.tst"), "quiet", stdout));
fprintf ("PASS: T04 exact set-operation tests\n");
assert (test (fullfile (test_dir, "t05_gamma_erf.tst"), "quiet", stdout));
fprintf ("PASS: T05 gamma and erf-family tests\n");
assert (test (fullfile (test_dir, "t06_special_function_firewall.tst"), "quiet", stdout));
fprintf ("PASS: T06 special-function backend audit and firewall tests\n");
assert (test (fullfile (test_dir, "t07_serialization.tst"), "quiet", stdout));
fprintf ("PASS: T07 exact serialization tests\n");
assert (test (fullfile (test_dir, "t08_graphics_3d.tst"), "quiet", stdout));
fprintf ("PASS: T08 3-D graphics boundary tests\n");
assert (test (fullfile (test_dir, "t09_random.tst"), "quiet", stdout));
fprintf ("PASS: T09 arbitrary-precision random-generation tests\n");
assert (test (fullfile (test_dir, "t10_interpolation.tst"), "quiet", stdout));
fprintf ("PASS: T10 one-dimensional interpolation tests\n");
assert (test (fullfile (test_dir, "t11_interp2.tst"), "quiet", stdout));
fprintf ("PASS: T11 two-dimensional interpolation tests\n");
assert (test (fullfile (test_dir, "t12_solvers.tst"), "quiet", stdout));
fprintf ("PASS: T12 nonlinear solver tests\n");
assert (test (fullfile (test_dir, "t13_quadrature.tst"), "quiet", stdout));
fprintf ("PASS: T13 arbitrary-precision quadrature tests\n");
assert (test (fullfile (test_dir, "t14_optimization.tst"), "quiet", stdout));
fprintf ("PASS: T14 arbitrary-precision optimization tests\n");
assert (test (fullfile (test_dir, "n07_closure.tst"), "quiet", stdout));
fprintf ("PASS: N07 numerical API closure and compatibility firewall tests\n");
assert (test (fullfile (test_dir, "mrdivide.tst"), "quiet", stdout));
fprintf ("PASS: N08 dense real and complex right-division tests\n");
assert (test (fullfile (test_dir, "script-compat", "s00.tst"), "quiet", stdout));
fprintf ("PASS: S00 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s01.tst"), "quiet", stdout));
fprintf ("PASS: S01 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s02.tst"), "quiet", stdout));
fprintf ("PASS: S02 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s03.tst"), "quiet", stdout));
fprintf ("PASS: S03 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s04.tst"), "quiet", stdout));
fprintf ("PASS: S04 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s05.tst"), "quiet", stdout));
fprintf ("PASS: S05 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s06.tst"), "quiet", stdout));
fprintf ("PASS: S06 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s07.tst"), "quiet", stdout));
fprintf ("PASS: S07 script compatibility tests\n");
assert (test (fullfile (test_dir, "script-compat", "s08.tst"), "quiet", stdout));
fprintf ("PASS: S08 script compatibility tests\n");
