test_dir = fileparts (mfilename ("fullpath"));
repo_root = fileparts (test_dir);

addpath (fullfile (repo_root, "inst"));
addpath (fullfile (repo_root, "src"));

assert (test (fullfile (test_dir, "build_probe.tst"), "quiet", stdout));
fprintf ("PASS: M01 build probe tests\n");
assert (test (fullfile (test_dir, "native_value.tst"), "quiet", stdout));
fprintf ("PASS: M02 native-value tests\n");
assert (test (fullfile (test_dir, "constructor.tst"), "quiet", stdout));
fprintf ("PASS: M03 public scalar constructor tests\n");
assert (test (fullfile (test_dir, "precision.tst"), "quiet", stdout));
fprintf ("PASS: M04 public precision tests\n");
assert (test (fullfile (test_dir, "conversion.tst"), "quiet", stdout));
fprintf ("PASS: M05 scalar conversion and display tests\n");
assert (test (fullfile (test_dir, "arithmetic.tst"), "quiet", stdout));
fprintf ("PASS: M06 scalar arithmetic tests\n");
assert (test (fullfile (test_dir, "matrix_storage.tst"), "quiet", stdout));
fprintf ("PASS: M07 native dense matrix storage tests\n");
assert (test (fullfile (test_dir, "gemm.tst"), "quiet", stdout));
fprintf ("PASS: M08 native MPFR Rgemm matrix multiplication tests\n");
assert (test (fullfile (test_dir, "gesv.tst"), "quiet", stdout));
fprintf ("PASS: M09 native MPFR Rgesv linear solve tests\n");
assert (test (fullfile (test_dir, "rgels.tst"), "quiet", stdout));
fprintf ("PASS: M15 native MPFR Rgels rectangular solve tests\n");
assert (test (fullfile (test_dir, "rank.tst"), "quiet", stdout));
fprintf ("PASS: M16 native rank-revealing rectangular solve tests\n");
assert (test (fullfile (test_dir, "chol.tst"), "quiet", stdout));
fprintf ("PASS: M17 native MPFR Rpotrf Cholesky tests\n");
assert (test (fullfile (test_dir, "qr.tst"), "quiet", stdout));
fprintf ("PASS: M18 native MPFR Rgeqrf/Rorgqr QR tests\n");
assert (test (fullfile (test_dir, "pivoted_qr.tst"), "quiet", stdout));
fprintf ("PASS: M19 native MPFR Rgeqp3/Rorgqr pivoted QR tests\n");
assert (test (fullfile (test_dir, "lu.tst"), "quiet", stdout));
fprintf ("PASS: M21 native MPFR Rgetrf LU tests\n");
assert (test (fullfile (test_dir, "matrix_inspection.tst"), "quiet", stdout));
fprintf ("PASS: M10 dense matrix inspection tests\n");
assert (test (fullfile (test_dir, "elementwise.tst"), "quiet", stdout));
fprintf ("PASS: M11 dense element-wise arithmetic tests\n");
assert (test (fullfile (test_dir, "structure.tst"), "quiet", stdout));
fprintf ("PASS: M12 dense transpose and reshape tests\n");
assert (test (fullfile (test_dir, "concat.tst"), "quiet", stdout));
fprintf ("PASS: M13 dense concatenation tests\n");
assert (test (fullfile (test_dir, "assignment.tst"), "quiet", stdout));
fprintf ("PASS: M14 dense indexed assignment tests\n");
assert (test (fullfile (test_dir, "release_closure.tst"), "quiet", stdout));
fprintf ("PASS: M22 real API and release closure tests\n");
assert (test (fullfile (test_dir, "complex_scalar.tst"), "quiet", stdout));
fprintf ("PASS: C01 complex scalar construction and conversion tests\n");
assert (test (fullfile (test_dir, "complex_matrix.tst"), "quiet", stdout));
fprintf ("PASS: C02 complex dense matrix tests\n");
assert (test (fullfile (test_dir, "complex_structural.tst"), "quiet", stdout));
fprintf ("PASS: C03 complex structural tests\n");
