## SPDX-License-Identifier: BSD-2-Clause

function svt_require_guard (required_bits, actual_bits, label)
  if (! isnumeric (required_bits) || ! isnumeric (actual_bits) ...
      || required_bits != fix (required_bits) ...
      || actual_bits != fix (actual_bits) || actual_bits < required_bits)
    error ("mplapack:svt:InsufficientConstructionPrecision", ...
           "%s needs at least %d bits (requested %d)", label, ...
           required_bits, actual_bits);
  endif
endfunction
