## SPDX-License-Identifier: BSD-2-Clause

function result = svt_make_pascal (case_id, parameters, work_bits)
  ## Construct either the lower Pascal factor Q or symmetric Pascal P.
  if (nargin != 3 || ! ischar (case_id) || ! isstruct (parameters) ...
      || ! isfield (parameters, "n") || ! isfield (parameters, "representation"))
    error ("mplapack:svt:InvalidPascalRequest", "invalid Pascal request");
  endif
  n = parameters.n;
  representation = char (parameters.representation);
  if (! isnumeric (n) || ! isscalar (n) || n != fix (n) || n < 1 ...
      || ! any (strcmp (representation, {"lower", "symmetric"})) ...
      || work_bits != fix (work_bits))
    error ("mplapack:svt:InvalidPascalParameters", ...
           "Pascal requires a positive n, valid representation, and integral precision");
  endif
  q_guard = n + 2;
  p_guard = 2 * n + 2;
  required_bits = max ([q_guard, p_guard]);
  svt_require_guard (required_bits, work_bits, "Pascal exact recurrence");

  saved_bits = mpbits ();
  cleanup = onCleanup (@() mpbits (saved_bits));
  mpbits (work_bits);
  q = mp (zeros (n, n));
  for i = 1:n
    q(i, 1) = mp (1);
    q(i, i) = mp (1);
    for j = 2:(i - 1)
      q(i, j) = q(i - 1, j - 1) + q(i - 1, j);
    endfor
  endfor
  p = mp (zeros (n, n));
  for i = 1:n
    p(i, 1) = mp (1);
    p(1, i) = mp (1);
  endfor
  for i = 2:n
    for j = 2:n
      p(i, j) = p(i, j - 1) + p(i - 1, j);
    endfor
  endfor
  if (strcmp (representation, "lower"))
    matrix = q;
  else
    matrix = p;
  endif
  relation = p - q * q';
  identity = svt_case_identity (case_id, "pascal", q, matrix, work_bits, ...
                                "exact_integer_recurrence", ...
                                "Pascal Q/P generated by Pascal addition");
  result = struct ("id", case_id, "tier", "A", "family", "pascal", ...
                   "parameters", parameters, "n", n, "representation", representation, ...
                   "Q", q, "P", p, "model", q, "A", matrix, ...
                   "q_times_q_transpose_error", relation, "analytic_values", [], ...
                   "rank", n, "full_rank", true, "det_model", mp (1), ...
                   "construction_guard_bits", required_bits, "identity", identity, ...
                   "status", "CONSTRUCTED");
  clear cleanup;
endfunction
