## SPDX-License-Identifier: BSD-2-Clause

function contract = svt_v0_contract (q)
  ## Runtime audit of the scalar assumptions used by the local verifier.
  if (! isnumeric (q) || ! isscalar (q) || ! isfinite (q) || q != fix (q) ...
      || q < 64 || q > 4096)
    error ("mplapack:svt:ContractPrecision", ...
           "Tier V requires 64 <= q <= 4096");
  endif
  saved_bits = mpbits ();
  cleanup = onCleanup (@() mpbits (saved_bits));
  mpbits (q);
  low_range = svt_pow2 (-32768);
  high_range = svt_pow2 (32768);
  primitive_low = svt_pow2 (-8192);
  primitive_high = svt_pow2 (8192);
  if (! isfinite (low_range) || ! isfinite (high_range) ...
      || low_range == mp (0) || high_range == mp (0) ...
      || low_range * high_range != mp (1) ...
      || primitive_low == mp (0) || ! isfinite (primitive_high))
    error ("mplapack:svt:ContractRange", ...
           "MPFR backend range audit failed");
  endif
  contract = struct ("schema", "svt-v0-contract-v1", "q", q, ...
                     "rounding", "MPFR_RNDN audited in local source", ...
                     "comparison", "finite MPFR comparison", ...
                     "minimum_primitive", primitive_low, ...
                     "maximum_primitive", primitive_high, ...
                     "backend_minimum", low_range, "backend_maximum", high_range, ...
                     "backend_subnormalization", "not observed in audited range", ...
                     "status", "AUDITED");
  clear cleanup;
endfunction
