% NEIGT Tier-S case index.
%
% This short numbered entry point preserves the historical family entry.
% It lists one runnable example per manifest case. The full measured wall is
% run by mp_neig_tiers ("smoke"/"demo") and by the repository test suite.
%
% Question: Which nonsymmetric eigensystem cases belong to Tier-S, and where is the
% detailed interpretation for each one?
% Steps: inspect the list, then run any matching .m file directly.
% Matching documentation: docs/examples/tiered/README.md

if (exist ("mpbits", "file") != 2)
  pkg load mplapack-interop
endif
example_root = fileparts (mfilename ("fullpath"));
suite_root = fullfile (example_root, "neig_tiers");
addpath (suite_root);
cleanup_path = onCleanup (@() rmpath (suite_root));

repo_root = fileparts (fileparts (mfilename ("fullpath")));
case_ids = {
  "OO53_REAL"; ...
  "OO53_PAIR"; ...
  "OO128_CLOSE"; ...
  "SIM_SIMPLE"; ...
  "SIM_REPEAT"; ...
  "SIM_JORDAN"; ...
  "SIM_TWO_JORDAN"; ...
  "TOEPLITZ"; ...
  "TOEPLITZ_SYM"; ...
  "FORSYTHE"; ...
  "FORSYTHE_SCALED"; ...
  "FORSYTHE_ZERO"
};
case_examples = {
  "examples/tiered/neig-tier-s/oo53_real.m"; ...
  "examples/tiered/neig-tier-s/oo53_pair.m"; ...
  "examples/tiered/neig-tier-s/oo128_close.m"; ...
  "examples/tiered/neig-tier-s/sim_simple.m"; ...
  "examples/tiered/neig-tier-s/sim_repeat.m"; ...
  "examples/tiered/neig-tier-s/sim_jordan.m"; ...
  "examples/tiered/neig-tier-s/sim_two_jordan.m"; ...
  "examples/tiered/neig-tier-s/toeplitz.m"; ...
  "examples/tiered/neig-tier-s/toeplitz_sym.m"; ...
  "examples/tiered/neig-tier-s/forsythe.m"; ...
  "examples/tiered/neig-tier-s/forsythe_scaled.m"; ...
  "examples/tiered/neig-tier-s/forsythe_zero.m"
};
case_docs = {
  "docs/examples/tiered/neig-tier-s/oo53_real.md"; ...
  "docs/examples/tiered/neig-tier-s/oo53_pair.md"; ...
  "docs/examples/tiered/neig-tier-s/oo128_close.md"; ...
  "docs/examples/tiered/neig-tier-s/sim_simple.md"; ...
  "docs/examples/tiered/neig-tier-s/sim_repeat.md"; ...
  "docs/examples/tiered/neig-tier-s/sim_jordan.md"; ...
  "docs/examples/tiered/neig-tier-s/sim_two_jordan.md"; ...
  "docs/examples/tiered/neig-tier-s/toeplitz.md"; ...
  "docs/examples/tiered/neig-tier-s/toeplitz_sym.md"; ...
  "docs/examples/tiered/neig-tier-s/forsythe.md"; ...
  "docs/examples/tiered/neig-tier-s/forsythe_scaled.md"; ...
  "docs/examples/tiered/neig-tier-s/forsythe_zero.md"
};

assert (numel (case_ids) == numel (case_examples));
assert (numel (case_ids) == numel (case_docs));
for index = 1:numel (case_ids)
  assert (exist (fullfile (repo_root, case_examples{index}), "file") == 2);
  assert (exist (fullfile (repo_root, case_docs{index}), "file") == 2);
  fprintf ("%s\t%s\t%s\n", case_ids{index}, case_examples{index}, case_docs{index});
endfor
fprintf ("NEIGT Tier-S index: %d cases.\n", numel (case_ids));

% Preserve the historical full-profile aggregator contract. The split files
% above are the teaching surface; this call remains the counted regression.
result = mp_neig_tiers ("smoke", struct ("tier", "S", "plot", false));
assert (result.scope_ok);
assert (strcmp (result.status, "NUMERICS_COMPLETE"));
fprintf ("NEIGT Tier-S smoke PASS: %d measured rows.\n", ...
         result.coverage.measured_eig_rows);
clear cleanup_path;
