% NEIGT Tier-A case index.
%
% This short numbered entry point preserves the historical family entry.
% It lists one runnable example per manifest case. The full measured wall is
% run by mp_neig_tiers ("smoke"/"demo") and by the repository test suite.
%
% Question: Which nonsymmetric eigensystem cases belong to Tier-A, and where is the
% detailed interpretation for each one?
% Steps: inspect the list, then run any matching .m file directly.
% Matching documentation: docs/examples/tiered/README.md

if (exist ("mpbits", "file") != 2)
  pkg load mplapack-interop
endif
example_root = fileparts (mfilename ("fullpath"));
suite_root = fullfile (example_root, "neig_tiers");
addpath (suite_root);
cleanup_path = onCleanup (@() rmpath (suite_root));

repo_root = fileparts (fileparts (mfilename ("fullpath")));
case_ids = {
  "HAD_BIDIAG"; ...
  "FRANK0"; ...
  "FRANK1"; ...
  "WILKINSON"; ...
  "GRCAR"; ...
  "MKS"; ...
  "MARKOV"; ...
  "PERRON_POS"; ...
  "HAD_COMPLEX"
};
case_examples = {
  "examples/tiered/neig-tier-a/had_bidiag.m"; ...
  "examples/tiered/neig-tier-a/frank0.m"; ...
  "examples/tiered/neig-tier-a/frank1.m"; ...
  "examples/tiered/neig-tier-a/wilkinson.m"; ...
  "examples/tiered/neig-tier-a/grcar.m"; ...
  "examples/tiered/neig-tier-a/mks.m"; ...
  "examples/tiered/neig-tier-a/markov.m"; ...
  "examples/tiered/neig-tier-a/perron_pos.m"; ...
  "examples/tiered/neig-tier-a/had_complex.m"
};
case_docs = {
  "docs/examples/tiered/neig-tier-a/had_bidiag.md"; ...
  "docs/examples/tiered/neig-tier-a/frank0.md"; ...
  "docs/examples/tiered/neig-tier-a/frank1.md"; ...
  "docs/examples/tiered/neig-tier-a/wilkinson.md"; ...
  "docs/examples/tiered/neig-tier-a/grcar.md"; ...
  "docs/examples/tiered/neig-tier-a/mks.md"; ...
  "docs/examples/tiered/neig-tier-a/markov.md"; ...
  "docs/examples/tiered/neig-tier-a/perron_pos.md"; ...
  "docs/examples/tiered/neig-tier-a/had_complex.md"
};

assert (numel (case_ids) == numel (case_examples));
assert (numel (case_ids) == numel (case_docs));
for case_index = 1:numel (case_ids)
  assert (exist (fullfile (repo_root, case_examples{case_index}), "file") == 2);
  assert (exist (fullfile (repo_root, case_docs{case_index}), "file") == 2);
  fprintf ("%s\t%s\t%s\n", case_ids{case_index}, case_examples{case_index}, case_docs{case_index});
endfor
fprintf ("NEIGT Tier-A index: %d cases.\n", numel (case_ids));

% Preserve the historical full-profile aggregator contract. The split files
% above are the teaching surface; this call remains the counted regression.
result = mp_neig_tiers ("smoke", struct ("tier", "A", "plot", false));
assert (result.scope_ok);
assert (strcmp (result.status, "NUMERICS_COMPLETE"));
fprintf ("NEIGT Tier-A smoke PASS: %d measured rows.\n", ...
         result.coverage.measured_eig_rows);
clear cleanup_path;
