% SVT Tier-A case index.
%
% This short numbered entry point preserves the historical family entry.
% It lists one runnable example per manifest case. The full measured wall is
% run by mp_svd_tiers ("smoke"/"demo") and by the repository test suite.
%
% Question: Which singular-value cases belong to Tier-A, and where is the
% detailed interpretation for each one?
% Steps: inspect the list, then run any matching .m file directly.
% Matching documentation: docs/examples/tiered/README.md

if (exist ("mpbits", "file") != 2)
  pkg load mplapack-interop
endif
example_root = fileparts (mfilename ("fullpath"));
suite_root = fullfile (example_root, "svd_tiers");
addpath (suite_root);
cleanup_path = onCleanup (@() rmpath (suite_root));

repo_root = fileparts (fileparts (mfilename ("fullpath")));
case_ids = {
  "A1-PASCAL-LOWER"; ...
  "A1-PASCAL-SYM"; ...
  "A2-VAND"; ...
  "A3-BDI-RAW"; ...
  "A3-BDI-MIXED"; ...
  "A4-LAU-TALL"; ...
  "A4-LAU-WIDE"; ...
  "A4-LAU-COMPLEX"; ...
  "A5-GEO"; ...
  "A5-CLOSE"; ...
  "A5-REPEAT"; ...
  "A5-RANK4"; ...
  "A5-RANK5"; ...
  "A6-NRO-COMPANION"
};
case_examples = {
  "examples/tiered/svd-tier-a/pascal_lower.m"; ...
  "examples/tiered/svd-tier-a/pascal_sym.m"; ...
  "examples/tiered/svd-tier-a/vandermonde.m"; ...
  "examples/tiered/svd-tier-a/bidiag_raw.m"; ...
  "examples/tiered/svd-tier-a/bidiag_mixed.m"; ...
  "examples/tiered/svd-tier-a/lauchli_tall.m"; ...
  "examples/tiered/svd-tier-a/lauchli_wide.m"; ...
  "examples/tiered/svd-tier-a/lauchli_complex.m"; ...
  "examples/tiered/svd-tier-a/hadamard_geometric.m"; ...
  "examples/tiered/svd-tier-a/hadamard_close.m"; ...
  "examples/tiered/svd-tier-a/hadamard_repeat.m"; ...
  "examples/tiered/svd-tier-a/hadamard_rank4.m"; ...
  "examples/tiered/svd-tier-a/hadamard_rank5.m"; ...
  "examples/tiered/svd-tier-a/nro_companion.m"
};
case_docs = {
  "docs/examples/tiered/svd-tier-a/pascal_lower.md"; ...
  "docs/examples/tiered/svd-tier-a/pascal_sym.md"; ...
  "docs/examples/tiered/svd-tier-a/vandermonde.md"; ...
  "docs/examples/tiered/svd-tier-a/bidiag_raw.md"; ...
  "docs/examples/tiered/svd-tier-a/bidiag_mixed.md"; ...
  "docs/examples/tiered/svd-tier-a/lauchli_tall.md"; ...
  "docs/examples/tiered/svd-tier-a/lauchli_wide.md"; ...
  "docs/examples/tiered/svd-tier-a/lauchli_complex.md"; ...
  "docs/examples/tiered/svd-tier-a/hadamard_geometric.md"; ...
  "docs/examples/tiered/svd-tier-a/hadamard_close.md"; ...
  "docs/examples/tiered/svd-tier-a/hadamard_repeat.md"; ...
  "docs/examples/tiered/svd-tier-a/hadamard_rank4.md"; ...
  "docs/examples/tiered/svd-tier-a/hadamard_rank5.md"; ...
  "docs/examples/tiered/svd-tier-a/nro_companion.md"
};

assert (numel (case_ids) == numel (case_examples));
assert (numel (case_ids) == numel (case_docs));
for index = 1:numel (case_ids)
  assert (exist (fullfile (repo_root, case_examples{index}), "file") == 2);
  assert (exist (fullfile (repo_root, case_docs{index}), "file") == 2);
  fprintf ("%s\t%s\t%s\n", case_ids{index}, case_examples{index}, case_docs{index});
endfor
fprintf ("SVT Tier-A index: %d cases.\n", numel (case_ids));

% Preserve the historical full-profile aggregator contract. The split files
% above are the teaching surface; this call remains the counted regression.
result = mp_svd_tiers ("smoke", struct ("tier", "A", "plot", false));
assert (result.scope_ok);
assert (strcmp (result.status, "PASS"));
fprintf ("SVT Tier-A smoke PASS: %d measured rows.\n", ...
         result.measured_svd_rows);
clear cleanup_path;
