% Prove the finite solve reduction C=B^(-1)A by the stated Neumann bound.
% A, B, RB and C0 are all point MP values at the current evaluation precision;
% RB and C0 remain candidate calculations, never exact substitutions.
function result = net_v_a2_reduction (A, B, RB, C0, q)
  net_iv_q (q);
  if (nargin != 5 || ! isa (A, "mp") || ! isa (B, "mp") ...
      || ! isa (RB, "mp") || ! isa (C0, "mp") || rows (A) != columns (A) ...
      || ! isequal (size (A), size (B)) || ! isequal (size (A), size (RB)) ...
      || ! isequal (size (A), size (C0)) || ! all (isfinite (A(:))) ...
      || ! all (isfinite (B(:))) || ! all (isfinite (RB(:))) ...
      || ! all (isfinite (C0(:))))
    error ("mplapack:neigt:VA2", "invalid finite-pencil reduction inputs");
  endif
  n = rows (A);
  A_box = net_iv_cmatrix_point (A, q);
  B_box = net_iv_cmatrix_point (B, q);
  RB_box = net_iv_cmatrix_point (RB, q);
  C0_box = net_iv_cmatrix_point (C0, q);
  e_box = net_iv_cmatrix_sub (net_iv_cmatrix_eye (n, q), ...
                              net_iv_cmatrix_mul (RB_box, B_box, q), q);
  e = net_iv_cmatrix_inf_upper (e_box, q);
  residual_box = net_iv_cmatrix_sub (A_box, ...
    net_iv_cmatrix_mul (B_box, C0_box, q), q);
  f_box = net_iv_cmatrix_mul (RB_box, residual_box, q);
  f = net_iv_cmatrix_inf_upper (f_box, q);
  denominator = net_iv_primitive ("sub", mp (1), e, q);
  result = struct ("method", "neigt_verified_finite_pencil_v1", ...
    "paper_algorithm_reproduction", false, "status", "INCONCLUSIVE", ...
    "pass", false, "B_nonsingular", false, "eB", e, "fB", f, ...
    "denominator", denominator.lo, "B_inverse_residual", e_box, ...
    "A_minus_BC0", residual_box, "RB_A_minus_BC0", f_box, ...
    "etaB", mp ("NaN"), "A_box", A_box, "B_box", B_box, ...
    "C0_box", C0_box, "C_box", [], "candidate_RB", RB, ...
    "candidate_C0", C0);
  if (e >= mp (1) || denominator.lo <= mp (0))
    result.status = "INCONCLUSIVE_B_NONSINGULARITY";
    return;
  endif
  eta = net_iv_primitive ("div", f, denominator.lo, q).hi;
  result.etaB = eta;
  result.C_box = net_v_a2_expand_modulus (C0_box, eta, q);
  result.B_nonsingular = true;
  result.pass = true;
  result.status = "CERTIFIED_B_NONSINGULAR_AND_REDUCTION";
endfunction
