% Markov/Perron ordinary and stationary-vector audit.
function result = net_markov_audit (n, epsilon_exponent, bits, reference_bits)
  markov = net_markov_model (n, epsilon_exponent, bits);
  perron = net_perron_model (n, epsilon_exponent, bits);
  markov_reference = net_markov_reference (markov, reference_bits, ...
                                           reference_bits + 64, false);
  perron_reference = net_markov_reference (perron.markov, reference_bits, ...
                                           reference_bits + 64, true);
  saved_bits = mpbits ();
  unwind_protect
    mpbits (reference_bits + 64);
    [V, D, W] = eig (markov.P_frozen, "nobalance");
    markov_metrics = net_metrics (markov.P_frozen, V, D, W, ...
                                   perron_reference.values2 / (mp (3) / mp (2)));
    [Vp, Dp, Wp] = eig (perron.A_frozen, "nobalance");
    perron_metrics = net_metrics (perron.A_frozen, Vp, Dp, Wp, ...
                                   perron_reference.values2);
    row_sums = markov.P_model * mp (ones (n, 1));
    positive_markov = all (markov.P_model(:) > mp (0));
    positive_perron = all (perron.A_model(:) > mp (0));
    r_difference = max (abs (markov_reference.stationary_formula - ...
                             transpose (markov.r)));
    perron_right = perron.D * mp (ones (n, 1));
    perron_left = perron.D_inverse * transpose (markov_reference.stationary_formula);
    perron_right = perron_right / sum (perron_right);
    perron_left = perron_left / (transpose (perron_left) * perron_right);
    right_equation = perron.A_model * perron_right ...
      - perron.perron_scale * perron_right;
    left_equation = transpose (perron_left) * perron.A_model ...
      - perron.perron_scale * transpose (perron_left);
    result = struct ("status", "MEASURED", "markov", markov, ...
      "perron", perron, "markov_reference", markov_reference, ...
      "perron_reference", perron_reference, "markov_metrics", markov_metrics, ...
      "perron_metrics", perron_metrics, "row_sums", row_sums, ...
      "row_sum_exact", all (row_sums == mp (1)), ...
      "positive_markov", positive_markov, "positive_perron", positive_perron, ...
      "r_difference_max", r_difference, ...
      "perron_right", perron_right, "perron_left", perron_left, ...
      "perron_right_equation", right_equation, ...
      "perron_left_equation", left_equation, ...
      "source", "A6_MARKOV_PERRON_AUDIT");
  unwind_protect_cleanup
    mpbits (saved_bits);
  end_unwind_protect
endfunction
