% Construct a closed complex rectangle from real/imaginary endpoints.
function result = net_iv_complex (rl, rh, il, ih)
  if (nargin != 4 || ! isa (rl, "mp") || ! isa (rh, "mp") ...
      || ! isa (il, "mp") || ! isa (ih, "mp") ...
      || ! isscalar (rl) || ! isscalar (rh) || ! isscalar (il) || ! isscalar (ih) ...
      || ! isfinite (rl) || ! isfinite (rh) || ! isfinite (il) || ! isfinite (ih) ...
      || rl > rh || il > ih)
    error ("mplapack:neigt:Rectangle", "invalid complex rectangle");
  endif
  result = struct ("kind", "complex", "rl", rl, "rh", rh, "il", il, "ih", ih);
endfunction
