% Ordinary forward and condition audit for one S3 representation.
function result = net_toeplitz_audit (fixture, reference_bits)
  if (nargin != 2 || ! isstruct (fixture) || ! isfield (fixture, "A") ...
      || ! isfield (fixture, "B_symmetric"))
    error ("mplapack:neigt:Toeplitz", "invalid Toeplitz audit fixture");
  endif
  reference = net_toeplitz_reference (fixture.n, fixture.b, reference_bits);
  saved_bits = mpbits ();
  unwind_protect
    mpbits (max (saved_bits, fixture.bits));
    [VB, DB, WB] = eig (fixture.B_symmetric, "nobalance");
    symmetric_values = diag (DB);
    symmetric_match = net_match (symmetric_values, reference.eigenvalues, ...
                                  "absolute");
    if (strcmp (fixture.representation, "original"))
      [Vn, Dn, Wn] = eig (fixture.A, "nobalance");
      [Vb, Db, Wb] = eig (fixture.A, "balance");
      nobalance_metrics = net_metrics (fixture.A, Vn, Dn, Wn, ...
                                       reference.eigenvalues);
      balance_metrics = net_metrics (fixture.A, Vb, Db, Wb, ...
                                     reference.eigenvalues);
    else
      [Vn, Dn, Wn] = eig (fixture.A, "nobalance");
      nobalance_metrics = net_metrics (fixture.A, Vn, Dn, Wn, ...
                                       reference.eigenvalues);
      balance_metrics = nobalance_metrics;
    endif
    condition_A = cond (fixture.A);
    condition_D = cond (fixture.D);
    similarity_condition = net_pow2 (fixture.b * (fixture.n - 1), fixture.bits);
    condition_separation = struct (...
      "matrix_A", condition_A, "scaling_D", condition_D, ...
      "similarity_scaling_bound", similarity_condition, ...
      "individual_eigenvalue", reference.condition_numbers, ...
      "matrix_and_eigenvalue_conditions_separate", true);
    result = struct (...
      "status", "MEASURED", "reference", reference, ...
      "symmetric_eig_match", symmetric_match, ...
      "nobalance_metrics", nobalance_metrics, ...
      "balance_metrics", balance_metrics, ...
      "condition_separation", condition_separation, ...
      "original_coordinate_label", fixture.representation);
  unwind_protect_cleanup
    mpbits (saved_bits);
  end_unwind_protect
endfunction
